language: de
pipeline:
  - name: WhitespaceTokenizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 40
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    epochs: 20
