version: "3.1"

language: de

assistant_id: rasa-intent-only

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 3
    max_ngram: 5
  - name: DIETClassifier
    epochs: 80
  - name: EntitySynonymMapper
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.1

policies: []
